export default {
  name: 'Орлого',
  isd: 0,
  isedit: 0,
  isadd: 0,
  ispaginate: 1,
  cols: [
    {
      t: 'Хүсэлтийн дугаар',
      k: 'req_code',
      tp: 'text',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'req_code',
      st: 'text',
    },
    {
      t: 'Утас',
      k: 'mobile_number',
      tp: 'text',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'mobile_number',
      st: 'text',
      ln: '/users/single#user_id',
    },
    {
      t: 'Харилцагчийн нэр',
      k: 'full_name',
      tp: 'text',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'full_name',
      st: 'text',
    },
    {
      t: 'Олгосон',
      k: 'start_date',
      tp: 'date',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'start_date',
      st: 'date',
    },
    {
      t: 'Дуусах',
      k: 'end_date',
      tp: 'date',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'end_date',
      st: 'date',
    },
    {
      t: 'Олгосон зээл',
      k: 'loan_amt',
      tp: 'amount',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'loan_amt',
      st: 'amount',
    },
    {
      t: 'Графикаар байх ёстой (ЗӨҮ)',
      k: 'should_be_principal',
      tp: 'amount',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'should_be_principal',
      st: 'amount',
    },
    {
      t: 'Одоо байгаа (ЗӨҮ)',
      k: 'to_pay_principal',
      tp: 'amount',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'to_pay_principal',
      st: 'amount',
    },
    {
      t: 'Үндсэн төлбөр зөрчсөн дүн',
      k: 'principal_late_amt',
      tp: 'amount',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'principal_late_amt',
      st: 'amount',
    },
    {
      t: 'Үндсэн төлбөр зөрчсөн хоног',
      k: 'principal_late_days',
      tp: 'amount',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'principal_late_days',
      st: 'amount',
    },
    {
      t: 'Хуримтлагдсан хүүний дүн',
      k: 'interest_late_amt',
      tp: 'amount',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'interest_late_amt',
      st: 'amount',
    },
    {
      t: 'Хүү зөрчсөн хоног',
      k: 'interest_late_days',
      tp: 'amount',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'interest_late_days',
      st: 'amount',
    },
    {
      t: 'Хэтэвч үлдэгдэл',
      k: 'wallet',
      tp: 'amount',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'wallet',
      st: 'amount',
    },
    {
      t: 'Шалтгаан',
      k: 'reason',
      tp: 'text',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'reason',
      st: 'text',
    },
    {
      t: 'Сунгасан эсэх',
      k: 'is_extend',
      tp: 'select',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'is_extend',
      st: 'text',

      opts: [
        {
          id: 'Тийм',
          name: 'Тийм',
        },
        {
          id: 'Үгүй',
          name: 'Үгүй',
        },
      ],
    },
    {
      t: 'Facebook',
      k: 'facebook_name',
      tp: 'text',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'facebook_name',
      st: 'text',
    },
    {
      t: 'Тэмдэглэл',
      k: 'description',
      tp: 'text',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'description',
      st: 'text',
    },
    {
      t: 'Оруулсан хэрэглэгч',
      k: 'username',
      tp: 'text',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'username',
      st: 'text',
    },
    {
      t: 'Оруулсан огноо',
      k: 'note_created_date',
      tp: 'date',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'note_created_date',
      st: 'date',
    },
    {
      t: 'Тэмдэглэл тоо',
      k: 'note_cnt',
      tp: 'amount',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'note_cnt',
      st: 'amount',
    },
    {
      t: 'Холбоо барих хүний дугаар',
      k: 'relation_person_mobile',
      tp: 'text',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'relation_person_mobile',
      st: 'text',
    },
    {
      t: 'Холбоо барих хүний дугаар 2',
      k: 'relation_person_mobile1',
      tp: 'text',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'relation_person_mobile1',
      st: 'text',
    },
    {
      t: 'Зээлдүүлэгч',
      k: 'loan_username',
      tp: 'text',
      w: '10%',
      s: 1,
      isc: 1,
      sk: 'loan_username',
      st: 'text',
    },
  ],
};
