export default {
  name: "Орлого",
  isd: 0,
  isedit: 0,
  isadd: 0,
  ispaginate: 1,
  cols: [
    {
      t: "Хүсэлтийн дугаар",
      k: "req_code",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "req_code",
      st: "text",
    },
    {
      t: "Утас",
      k: "mobile_number",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "mobile_number",
      st: "text",
      ln: "/users/single#user_id",
    },
    {
      t: "Харилцагчийн нэр",
      k: "full_name",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "full_name",
      st: "text",
    },
    {
      t: "Регистр",
      k: "register_number",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "register_number",
      st: "text",
    },
    {
      t: "Зээлийн хугацаа",
      k: "loan_term",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "loan_term",
      st: "text",
    },
    {
      t: "Олгосон",
      k: "start_date",
      tp: "date",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "start_date",
      st: "date",
    },
    {
      t: "Дуусах",
      k: "end_date",
      tp: "date",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "end_date",
      st: "date",
    },
    {
      t: "Cyнгалт хийсэн",
      k: "extend_start_date",
      tp: "date",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "end_date",
      st: "date",
    },
    {
      t: "Сунгалт дуусах",
      k: "extend_end_date",
      tp: "date",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "end_date",
      st: "date",
    },
    {
      t: "Олгосон зээл",
      k: "loan_amt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "loan_amt",
      st: "amount",
    },
    {
      t: "Үндсэн зээл",
      k: "remaining_total",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "remaining_total",
      st: "amount",
    },
    {
      t: "Хүү",
      k: "remaining_fee",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "remaining_fee",
      st: "amount",
    },
    {
      t: "Алданги",
      k: "penalty",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "penalty",
      st: "amount",
    },
    {
      t: "Сунгалтын хураамж",
      k: "extend_fee",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "extend_fee",
      st: "amount",
    },
    {
      t: "Бүгд",
      k: "total_amt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "total_amt",
      st: "amount",
    },
    {
      t: "Хүүний хувь",
      k: "rate_amt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "rate_amt",
      st: "amount",
    },
    {
      t: "Зээлдүүлэгч",
      k: "loan_username",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "loan_username",
      st: "text",
      ln: "/users/single#loan_user_id",
    },
    {
      t: "Сунгалтын давтамж",
      k: "extend_cnt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "extend_cnt",
      st: "amount",
    },
    {
      t: "Төлөв",
      k: "status_name",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "status_name",
      st: "text",
      opts: [
        {
          id: "Төлөгдөж дууссан",
          name: "Төлөгдөж дууссан",
        },
        {
          id: "Сунгасан",
          name: "Сунгасан",
        },
        {
          id: "Хоцорсон сунгалт",
          name: "Хоцорсон сунгалт",
        },
        {
          id: "Төлөгдөж дуусаагүй",
          name: "Төлөгдөж дуусаагүй",
        },
      ],
    },
  ],
};
