import educationLevel from "./common/educationLevel";
import gender from "./common/gender";

export default {
  name: "Орлого",
  isd: 0,
  isedit: 0,
  isadd: 0,
  ispaginate: 1,
  cols: [
    {
      t: "Хүсэлтийн дугаар",
      k: "req_code",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "req_code",
      st: "text",
    },
    {
      t: "Овог нэр",
      k: "full_name",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "full_name",
      st: "text",
    },
    {
      t: "Утас",
      k: "mobile_number",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "mobile_number",
      st: "text",
      ln: "/users/single#user_id",
    },
    {
      t: "Регистр",
      k: "register_number",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "register_number",
      st: "text",
    },
    {
      ...gender,
      sk: "gender_id",
    },
    {
      t: "Нас",
      k: "age",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "age",
      st: "amount",
    },
    {
      ...educationLevel,
    },
    {
      t: "Олгосон зээл",
      k: "loan_amt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 0,
      sk: "family_count",
      st: "amount",
    },
    {
      t: "Зээлийн хугацаа",
      k: "loan_term",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "loan_term",
      st: "text",
    },
    {
      t: "Хүүгийн хувь",
      k: "rate_amt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "rate_amt",
      st: "amount",
    },
    {
      t: "Эхлэх огноо",
      k: "start_date",
      tp: "date",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "start_date",
      st: "date",
    },
    {
      t: "Дуусах огноо",
      k: "end_date",
      tp: "date",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "end_date",
      st: "date",
    },
    {
      t: "Сүүлийн төлөлт огноо",
      k: "last_payment_date",
      tp: "date",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "last_payment_date",
      st: "date",
    },
    {
      t: "Үндсэн зээлийн үлдэгдэл",
      k: "remaining_total",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "remaining_total",
      st: "amount",
    },
    {
      t: "Хүү(Төлсөн)",
      k: "paid_interest",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "paid_interest",
      st: "amount",
    },
    {
      t: "Хүү(Хөнгөлөлт)",
      k: "non_interest",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "non_interest",
      st: "amount",
    },
    {
      t: "Алданги(Төлсөн)",
      k: "paid_interest",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "paid_interest",
      st: "amount",
    },
    {
      t: "Алданги(Хөнгөлөлт)",
      k: "non_penalty",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "non_penalty",
      st: "amount",
    },
    {
      t: "Шимтгэл(Төлсөн)",
      k: "paid_issue_fee",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "paid_issue_fee",
      st: "amount",
    },
    {
      t: "Хүү(Хуримтлагдсан)",
      k: "remaining_interest",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "remaining_interest",
      st: "amount",
    },
    {
      t: "Алданги(Хуримтлагдсан)",
      k: "remaining_penalty",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "remaining_penalty",
      st: "amount",
    },
    {
      t: "Шимтгэл(Хуримтлагдсан)",
      k: "remaining_fee",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "remaining_fee",
      st: "amount",
    },
    {
      t: "Ашигласан хоног",
      k: "used_day",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "used_day",
      st: "amount",
    },
    {
      t: "Зээлийн хоног",
      k: "loan_day",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "loan_day",
      st: "amount",
    },
    {
      t: "Давтамж",
      k: "loan_cnt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "loan_cnt",
      st: "amount",
    },
    {
      t: "Cунгасан эсэх",
      k: "is_extend",
      tp: "select",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "is_extend_id",
      st: "number",

      opts: [
        {
          id: 1,
          name: "Тийм",
        },
        {
          id: 0,
          name: "Үгүй",
        },
      ],
    },
    {
      t: "Сунгалтын давтамж",
      k: "extend_cnt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "extend_cnt",
      st: "amount",
    },
    {
      t: "Зээлдүүлэгч",
      k: "loan_username",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "loan_username",
      st: "text",
      ln: "/users/single#loan_user_id",
    },
    {
      t: "Төлөв",
      k: "loan_status",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "loan_status",
      st: "text",
      ln: "/users/single#loan_user_id",
      opts: [
        {
          id: "Төлөгдөж дууссан",
          name: "Төлөгдөж дууссан",
        },
        {
          id: "Хугацаа хэтэрсэн",
          name: "Хугацаа хэтэрсэн",
        },
        {
          id: "Төлөгдөж буй",
          name: "Төлөгдөж буй",
        },
      ],
    },
  ],
};
