export default {
  name: "Орлого",
  isd: 0,
  isedit: 0,
  isadd: 0,
  ispaginate: 1,
  cols: [
    {
      t: "Зээлдэгч",
      k: "borrower",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "borrower",
      st: "text",
      ln: "/users/single#user_id",
    },
    {
      t: "Төлөх огноо",
      k: "due_date",
      tp: "date",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "due_date",
      st: "date",
    },
    {
      t: "Төлсөн огноо",
      k: "created_at",
      tp: "date",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "created_at",
      st: "date",
    },
    {
      t: "Үндсэн төлбөр",
      k: "principal_amt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "principal_amt",
      st: "amount",
    },
    {
      t: "Хүүгийн төлбөр",
      k: "interest_amt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "interest_amt",
      st: "amount",
    },
    {
      t: "Хугацаанаасаа өмнө төлсөн",
      k: "is_paid_before",
      tp: "select",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "is_paid_before",
      st: "text",
      opts: [
        {
          id: "Тийм",
          name: "Тийм",
        },
        {
          id: "Үгүй",
          name: "Үгүй",
        },
      ],
    },
    {
      t: "Нийт төлөх",
      k: "payment_amt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "payment_amt",
      st: "amount",
    },

    {
      t: "Нийт төлсөн",
      k: "total_paid",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "total_paid",
      st: "amount",
    },

    {
      t: "Алданги",
      k: "penalty_amt",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "penalty_amt",
      st: "amount",
    },
    {
      t: "Хэд хоногийн өмнө төлсөн",
      k: "diff_date",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "diff_date",
      st: "amount",
    },
  ],
};
