import businessSector from "./common/businessSector";
import educationLevel from "./common/educationLevel";
import home from "./common/home";
import isMyApartment from "./common/isMyApartment";

export default {
  name: "Орлого",
  isd: 0,
  isedit: 0,
  isadd: 0,
  ispaginate: 1,
  cols: [
    {
      t: "Регистр",
      k: "register_number",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "register_number",
      st: "text",
    },
    {
      t: "Овог",
      k: "last_name",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "last_name",
      st: "text",
    },
    {
      t: "Нэр",
      k: "first_name",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "first_name",
      st: "text",
    },
    {
      t: "Утас",
      k: "mobile_number",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "mobile_number",
      st: "text",
      ln: "/users/single#user_id",
    },
    {
      t: "Имэйл",
      k: "email",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "email",
      st: "text",
    },
    {
      ...educationLevel,
    },
    {
      ...home,
    },
    {
      ...isMyApartment,
    },
    {
      t: "Өрхийн гишүүн",
      k: "family_count",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "family_count",
      st: "amount",
    },
    {
      t: "Орлого",
      k: "income",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "income",
      st: "amount",
    },
    {
      t: "Сард төлдөг зээлийн дүн",
      k: "outcome",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "outcome",
      st: "amount",
    },
    {
      ...businessSector,
      isc: 1,
    },
    {
      t: "Нийт ажилласан жил",
      k: "worked_year",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "worked_year",
      st: "amount",
    },
    {
      t: "Одоогийн байгууллага",
      k: "company_name",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "company_name",
      st: "text",
    },
    {
      t: "Одоогийн байгууллагадаа ажилласан жил",
      k: "worked_year_in_company",
      tp: "amount",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "worked_year_in_company",
      st: "amount",
    },
    {
      t: "Аймаг",
      k: "aimag_name",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "aimag_name",
      st: "text",
    },
    {
      t: "Сум",
      k: "sum_name",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "sum_name",
      st: "text",
    },
    {
      t: "Хороо",
      k: "khoroo_name",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "khoroo_name",
      st: "text",
    },
    {
      t: "Байр/гудамж",
      k: "address_bair",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "address_bair",
      st: "text",
    },
    {
      t: "Тоот",
      k: "address_toot",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "address_toot",
      st: "text",
    },
    {
      t: "Хаяг өөрчилөлтийн тоо",
      k: "address_change_count",
      tp: "number",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "address_change_count",
      st: "number",
    },
    {
      t: "Хаяг дээрээ бүртгэлтэй эсэх",
      k: "in_address",
      tp: "text",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "in_address",
      st: "text",
    },
    {
      t: "Тухайн хаяган дээрх хугацаа",
      k: "in_address_year",
      tp: "number",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "in_address_year",
      st: "number",
    },
    {
      t: "Огноо",
      k: "created_date",
      tp: "date",
      w: "10%",
      s: 1,
      isc: 1,
      sk: "created_date",
      st: "date",
    },
  ],
};
